### ISSUE TITLE
您复现的时候，500个epoch的结果很最好的结果相差很多吗？

### ISSUE THREAD

**Issue by rubyzhangyajie** [xiami2019/Image-Retrieve#2]

**Comment by xiami2019** [comment]
有点忘了，好像差挺多的

**Comment by rubyzhangyajie** [comment]
好的，谢谢，还有一个小问题需要咨询一下，就是您处理数据集的时候为什么要把图片先放大到256，再裁剪成224的尺寸呢？因为这样做的话相当于把图片中的目标放大了，网络会更加容易识别一些，这样操作在检索任务中是允许的吗？

**Comment by xiami2019** [comment]
允许的，这是CV的常规操作，因为数据集图片的大小和通道数可能是不确定的，而且不同神经网络的输入尺寸也不同
